### ISSUE TITLE
[WARNING] Gauge degrees of freedom are NOT fixed!

### ISSUE THREAD

**Issue by AlexanderOnly** [potfit/potfit#69]
I have got this WARNING when I using POTFIT, and  I don't know how to 'fix the Gauge degrees' or change the 'box size/cutoff distance' to avoid this warning... Any help are highly appreciated!

[WARNING] Gauge degrees of freedom are NOT fixed!
[WARNING] The box size of configuration 1 is smaller than the cutoff distance.
[WARNING]   Using additional periodic images for energy and force calculations.

**Comment by p-bro** [comment]
There are two issues here:

- Gauge degrees of freedom are a property of EAM potentials, you can shift contributions from pair to embedding terms and scale the transfer and embedding functions. The gauge degrees can be fixed by e.g. specifying the embedding energy gradient at a certain value. If using analytic potentials, the functional form of the potential may constrain and/or even fix those degrees of freedom. The purpose of the warning is to alert you to the fact that you may get different potentials that are physically equivalent.

- Box size: If your simulation box for reference configuration is smaller than the cutoff radius for your potential, an atom will interact with periodic copies of itself. potfit can handle this correctly, but it may have consequences on the pair distribution function. Again - it's just a warning. If you don't want to see it, use larger reference configurations.

**Comment by AlexanderOnly** [comment]
> There are two issues here:
> 
> * Gauge degrees of freedom are a property of EAM potentials, you can shift contributions from pair to embedding terms and scale the transfer and embedding functions. The gauge degrees can be fixed by e.g. specifying the embedding energy gradient at a certain value. If using analytic potentials, the functional form of the potential may constrain and/or even fix those degrees of freedom. The purpose of the warning is to alert you to the fact that you may get different potentials that are physically equivalent.
> * Box size: If your simulation box for reference configuration is smaller than the cutoff radius for your potential, an atom will interact with periodic copies of itself. potfit can handle this correctly, but it may have consequences on the pair distribution function. Again - it's just a warning. If you don't want to see it, use larger reference configurations.

**Comment by AlexanderOnly** [comment]
> There are two issues here:
> 
> * Gauge degrees of freedom are a property of EAM potentials, you can shift contributions from pair to embedding terms and scale the transfer and embedding functions. The gauge degrees can be fixed by e.g. specifying the embedding energy gradient at a certain value. If using analytic potentials, the functional form of the potential may constrain and/or even fix those degrees of freedom. The purpose of the warning is to alert you to the fact that you may get different potentials that are physically equivalent.
> * Box size: If your simulation box for reference configuration is smaller than the cutoff radius for your potential, an atom will interact with periodic copies of itself. potfit can handle this correctly, but it may have consequences on the pair distribution function. Again - it's just a warning. If you don't want to see it, use larger reference configurations.

Thank you!
