### ISSUE TITLE
Example for generating a tabulated potential?

### ISSUE THREAD

**Issue by anneb101** [potfit/potfit#72]
Hello potfit community,

I am interested in using potfit to generate a tabulated potential as described on this page:
https://www.potfit.net/wiki/doku.php?id=models:tabulated

However, the provided downloadable example focuses on the generation of an analytic LJ potential:
![image](https://user-images.githubusercontent.com/20980002/91084229-a8df5180-e619-11ea-956f-ec8f73933bda.png)

Are there any ready-made examples for a tabulated potential available?

Thank you,
Anne

**Comment by dschopf** [comment]
I'm afraid there is nothing available at the moment. 

The problem for tabulated potentials is always the starting potential. For a very simple potential you might just create it from scratch by calculating a few sampling points by hand and writing them to your input file. And then there is the old (and maybe not even working) `genpot.awk` script in `util/old/awk` which creates tabulated potentials out of thin air (well almost).

On the other hand it should be quite easy to modify the `makeapot` utility script to create tabulated potentials instead of analytic ones.

Do you have specific applications in mind or are you just trying to get familiar with potfit in general?

**Comment by p-bro** [comment]
Adding to that, the AlNiCo, CaCd, MgZn potentials in the potfit potentials page https://www.potfit.net/wiki/doku.php?id=potentials:main could serve as template. The respective manual pages https://www.potfit.net/wiki/doku.php?id=potfiles:format4 and https://www.potfit.net/wiki/doku.php?id=potfiles:format3 also contain links to example files.

If you really want to start from scratch, then you have to keep in mind that in general, all parameters have to matter (if the choice of a parameter does not impact the fit, then that parameter can be chosen arbitrarily). This could be an issue in EAM potentials. If for example the embedding function is constant, then the value of the transfer function does not matter at all.

**Comment by anneb101** [comment]
Hi @dschopf and @p-bro, thank you for the responses. I am not using parameters, but a few energy vs distance data points from QM-level calculations. I was looking for a tool that could use these data points to generate splines appropriate for use in MD. 

- Do the above examples generate splines?

- The format 4 page (https://www.potfit.net/wiki/doku.php?id=potfiles:format4) describes some of the lines in the file:
```
r_0     f(r_0)
r_1     f(r_1)
...
r_steps f(r_steps)
```

- However, the format 4 file (https://www.potfit.net/wiki/lib/exe/fetch.php?media=format_4g.pot.txt) appears to have more lines and blocks; is there documentation available on what all parts of the file mean?

- I am a bit stuck on what steps to take to execute these input files. It appears that makeapot (https://www.potfit.net/wiki/doku.php?id=utilities:makeapot) is designed for analytic potential; what modifications need to be done to execute the generation of a tabulated potential?

Thank you,
Anne

**Comment by dschopf** [comment]
I am not sure I understand what you are looking for. From your comment it seems to me that you already have your potential and are looking for a "mathematical tool" which will interpolate these data points for you? Sure potfit could do that for you. Just plug your data points into a potential file and run potfit without optimization. At the moment we only support IMD as an MD potential format and that is probably not what you are looking for.

The example is pretty minimalistic and assumes some things are know to the reader, which is probably not the best approach for that page. I will try to extend the page to explain the format in greater detail.

Since the python module used in `makeapot` already has the analytic formula for each available potential function, it could be modified to write some sampling points instead of the actual parameters. But judging from your feedback this is probably not what you actuall want/need.

**Comment by dschopf** [comment]
I have updated the format pages a little, does this help?

**Comment by anneb101** [comment]
Thank you very much for updating the potential file annotations - it is very clear now.

Sorry if I was not clear earlier, but I was asking if I can input a set of data points into potfit, and if it then generates spline coefficients that can be used to interpolate between the data points. If so, that is the mathematical tool that I am looking for. This is what I had assumed was meant by the generation of tabulated potentials. I was seeing if this is a functionality already present in an existing potfit script. 

Thank you,
Anne

**Comment by p-bro** [comment]
Potfit requires a potential in one of the supported formats (analytic - 0, tabulated equidistant - 3, tabulated non-equidistant - 4 or KIM - 5). For formats 3 and 4, the actual potential is a spline defined by the tabulated values plus either their gradients at the boundaries or the fact that these are natural splines. Potfit then internally calculates the table of second derivatives, which is necessary to calculate interpolated function values and gradients, but there is no easy way to access these (and that's no big secret - potfit just uses a rather standard spline algorithm). Potfit can also create more densely tabulated potential tables, in the plot file https://www.potfit.net/wiki/doku.php?id=output:plotfile, and files for use in LAMMPS and IMD, but it should be noted that these are only approximations to the potfit internal potential.

All the code for splines is in splines.c and splines.h - the spline_?? functions initialise the splines, and the splint_* functions provide the interpolations.

Hope that helps,

Peter

**Comment by anneb101** [comment]
Thank you for the clarifications and help. I will look into the splines.c/h files.
Anne
