### ISSUE TITLE
[WARNING] F does not depend on xi[0], fit impossible!

### ISSUE THREAD

**Issue by krishnansiddharth** [potfit/potfit#77]
Hi potfit community,

While performing Powell minimization, potfit throws the warning at me following which it fails to perform the minimization. I am trying to build an EAM potential for a single element. Since I was facing this error, I decided to use the final potential from the paper I was trying to reproduce as my starting potential. Potfit continues to throw the same error. 

Has anyone has faced similar issues and successfully resolved it? 

Thanks and Regards,
Siddharth 

PS: I have attached the files I am running. 
[param.txt](https://github.com/potfit/potfit/files/5399773/param.txt)

[configiration.txt](https://github.com/potfit/potfit/files/5399780/configiration.txt)
[pot_start_2.txt](https://github.com/potfit/potfit/files/5399781/pot_start_2.txt)

**Comment by dschopf** [comment]
This is a rather common error, which happens when changing a potential value at a certain sampling point does not change the error sum at all. What this is means is that the potential value at `xi[0]`, which is the very first sampling point, does not have any contribution to the error sum. If this happens, the optimization algorithm cannot continue.

You can easily see this when you plot your potential and the radial distribution function of your configurations:
![plot](https://user-images.githubusercontent.com/3724829/96739420-114f7280-13c0-11eb-80d6-d5fa2d02a266.jpg)
The leftmost sampling point is not supported at all by the reference configurations.

My recommendation would be the increase the size of your set of reference configurations. Especially include such which have short interatomic distances to support the sampling point at r = 2.073.

**Comment by krishnansiddharth** [comment]
If the leftmost point is the sole problem then removing it should solve the error right? 

I did so but the same error is thrown at me. 

Thanks and Regards,
Siddharth

**Comment by dschopf** [comment]
If the same error occurs then most likely the reference data for the second data point is also not enough. I would strongly recommend to not remove any sampling points from the potential but adding more reference data. You are missing all the short range repulsive part of your potential, this will most likely never be stable in any MD simulation.
